[package]
name = "porecatu-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
arboard = "3"
dirs = "5"
png = "0.18"
porecatu-config = { path = "../porecatu-config" }
porecatu-core = { path = "../porecatu-core" }
porecatu-render = { path = "../porecatu-render" }
porecatu-term = { path = "../porecatu-term" }
winit = "0.30.13"
