[package]
name = "porecatu-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = "0.8"
dirs = "5"
serde_ignored = "0.1"

[dev-dependencies]
